### ISSUE TITLE
Unhandled 'error' event EPIPE

### ISSUE THREAD

**Issue by lax4mike** [gummesson/gulp-pandoc#4]
I tried pandoc using the exact example in the readme, but I'm getting an error:

	events.js:72
	        throw er; // Unhandled 'error' event
	              ^
	Error: write EPIPE
	    at errnoException (net.js:901:11)
	    at Object.afterWrite (net.js:718:19)

I'm using this version:

    "gulp-pandoc": "^0.2.1",

**Comment by macrozone** [comment]
try to install pandoc https://github.com/jgm/pandoc/releases
